name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      # fix corepack enabling pattern once landed
      # https://github.com/actions/setup-node/issues/1075#issuecomment-2165643488
      # https://github.com/actions/setup-node/pull/901
      - name: Setup Node.js
        id: setup-node-1
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version

      - name: Corepack enable
        id: corepack-enable
        run: corepack enable

      - name: Setup Node.js
        id: setup-node-2
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn

      - name: Install Dependencies
        id: yarn
        run: yarn

      - name: Check Format
        id: yarn-format-check
        run: yarn format:check

      - name: Lint
        id: yarn-lint
        run: yarn lint
